#!/bin/bash
sudo apt update -y
sudo apt install -y ruby wget nodejs npm
wget https://aws-codedeploy-us-east-2.s3.us-east-2.amazonaws.com/latest/install
chmod +x ./install
./install auto
sudo service codedeploy-agent start