#!/bin/bash
apt update -y
apt install -y ruby wget nodejs npm
wget https://aws-codedeploy-us-east-2.s3.us-east-2.amazonaws.com/latest/install
chmod +x ./install
./install auto
service codedeploy-agent start